name: Release

on:
  release:
    types: [ published ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Flutter
        uses: hrishikesh-kadam/setup-flutter@v1

      - name: Build
        run: |
          git clone https://${{ secrets.P_TOKEN }}@github.com/infumia/tuna.git
          cd tuna
          flutter config --enable-windows-desktop
          flutter build windows --dart-define="build_id=${{ github.event.release.tag_name }}" --dart-define="version=${{ github.event.release.tag_name }}"
          flutter pub run msix:create --version ${{ github.event.release.tag_name }}.0
          cd ${{ github.workspace }}
          mkdir win-build
          copy ${{ github.workspace }}\tuna\build\windows\runner\Release\tuna.msix win-build
          copy ${{ github.workspace }}\tuna\assets\certificate.pfx win-build
          copy ${{ github.workspace }}\tuna\assets\install.bat win-build

      - name: Zip Windows 10
        uses: thedoctor0/zip-release@master
        with:
          path: win-build\.
          filename: 'tuna-win10.zip'

      - name: Zip Windows 7
        uses: thedoctor0/zip-release@master
        with:
          path: ${{ github.workspace }}\tuna\build\windows\runner\Release\.
          filename: 'tuna-win7.zip'
          exclusions: '*.msix'

      - name: Upload files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tuna-win7.zip
            tuna-win10.zip
